### ISSUE TITLE
LLVM intrinsics

### ISSUE THREAD

**Issue by vks** [japaric/m#11]
What about using [LLVM intrinsics](http://llvm.org/docs/LangRef.html#standard-c-library-intrinsics)? The following intrinsics might be relevant: `sqrt`, `powi`, `sin`, `cos`, `pow`, `exp`, `exp2`, `log`, `log10`, `log2`, `fabs`, `floor`, `ceil`, `round`.

**Comment by japaric** [comment]
Sadly, it seems that calling those functions lower to e.g. `bl <expf>` where `expf` is an intrinsic that must be provided by the compiler-rt project. These particular intrinsics has not been yet implemented in [the Rust port of compiler-rt](https://github.com/rust-lang-nursery/compiler-builtins) so we can't use them without dependency on C code.

Also using these would require nightly as e.g. `intrinsics::expf` is unstable and compiling the `compiler-builtins` crate, when these intrinsics get implemented there, would also require nightly.

**Comment by japaric** [comment]
This crate has been deprecated in favor of the [libm] crate. This repository will be archived.

[libm]: https://github.com/japaric/libm
