### ISSUE TITLE
Corrode openlibm

### ISSUE THREAD

**Issue by japaric** [japaric/m#13]
[Corrode](https://github.com/jameysharp/corrode) is a C -> Rust converter. It doesn't work out of the box on openlibm due to jameysharp/corrode#100:

```
# this is one of the commands that `make` calls but with `corrode` instead of with `gcc`
$ corrode -fno-gnu89-inline -fno-builtin -O3 -fPIC -m64 -std=c99 -Wall -I$(pwd) -I$(pwd)/include -I$(pwd)/amd64 -I$(pwd)/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -I$(pwd)/ld80 -c src/e_acos.c -o e_acos.rs
<command-line>:0:1: warning: undefining "__LINE__"
("src/e_acos.c": line 69): illegal member access of incomplete type; check whether a real C compiler accepts this:
    gh_u.value
```

But I think it may be possible to replace or stub the use of unions that cause problems to make the translation work.

**Comment by anatol** [comment]
`openlibm` is full of number wrapping and overflowing number arithmetic. It is kinda norm for math libs written in C. But in Rust debug mode it causes an abort. I am not sure how corrode can find/convert such wrapping operations.

**Comment by Ixrec** [comment]
@anatol Is this a different kind of wrapping from the wrapping arithmetic that https://doc.rust-lang.org/std/num/struct.Wrapping.html does?

**Comment by anatol** [comment]
@Ixrec it is the same.

corrode have to learn how to find arithmetic operations that wrap numbers. And I am not sure if it possible to find it statically just by reading C code. In C code any arithmetic operation can wrap.

Thus even if `corode` can generate perfectly compilable rust code there are still some manual modifications are needed.

**Comment by japaric** [comment]
This crate has been deprecated in favor of the [libm] crate. This repository will be archived.

[libm]: https://github.com/japaric/libm
