### ISSUE TITLE
Implement Logarithms

### ISSUE THREAD

**Issue by Michael-F-Bryan** [japaric/m#14]
Are there any plans in the works for implementing something like `log10()` on floating point numbers?

**Comment by japaric** [comment]
Not from my side as I haven't found any need for them (yet). But porting is usually copy pasting the C implementation (openlibm's) and changing the C syntax into Rust syntax.

**Comment by japaric** [comment]
This crate has been deprecated in favor of the [libm] crate. This repository will be archived.

[libm]: https://github.com/japaric/libm
