### ISSUE TITLE
Import code from core

### ISSUE THREAD

**Issue by vks** [japaric/m#16]
There is a bunch of float code (only exposed on nightly) we could import from core, basically see the `BasicFloat` trait [here](https://github.com/vks/num/blob/351dfc638318af55026394913795196730bd3159/traits/src/float.rs#L10), notably `is_finite`, `is_normal`, `classify`, `signum`, `is_sign_{posi,nega}tive`, `recip`, `powi`, `to_degrees`, `to_radians`. Should we import it? The licensing situation would get a bit messy... On the other hand, most of the code is kind of trivial.

**Comment by japaric** [comment]
This crate has been deprecated in favor of the [libm] crate. This repository will be archived.

[libm]: https://github.com/japaric/libm
